-- Intentionally empty.
-- Monalyz ships no Auth identity, password, staff membership, fake position,
-- seeded transaction, or production-derived data. The optional local/CI clean
-- admin baseline is created after reset through `bun run demo:clean-admin`.
