-- Transfer review notes are optional for approvals. Rejections keep their
-- existing mandatory reason. Each intermediate approval queues one
-- idempotent progress email; the final approval keeps the existing completed
-- transfer email generated by the transfer status trigger.

alter table public.transactional_email_outbox
  drop constraint if exists transactional_email_outbox_template_key_check;

alter table public.transactional_email_outbox
  add constraint transactional_email_outbox_template_key_check
  check (
    template_key in (
      'transfer_submitted',
      'transfer_check_validated',
      'transfer_approved',
      'transfer_completed',
      'transfer_rejected',
      'transfer_failed',
      'loan_submitted',
      'loan_approved',
      'loan_disbursed',
      'loan_rejected',
      'loan_failed',
      'kyc_submitted',
      'kyc_information_requested',
      'kyc_resubmitted',
      'kyc_approved',
      'kyc_rejected'
    )
  );

create or replace function private.enqueue_transfer_check_validation_email()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  transfer_row public.transfer_intents;
  recipient_email text;
begin
  select transfer.*
  into transfer_row
  from public.transfer_intents as transfer
  where transfer.id = new.transfer_id;

  if not found then
    return new;
  end if;

  select profile.email
  into recipient_email
  from public.profiles as profile
  where profile.user_id = transfer_row.owner_id;

  if recipient_email is null then
    return new;
  end if;

  insert into public.transactional_email_outbox (
    event_key,
    recipient_id,
    recipient_email,
    template_key,
    entity_type,
    entity_id,
    payload
  ) values (
    'transfer_review_checks:' || new.id::text || ':completed',
    transfer_row.owner_id,
    recipient_email,
    'transfer_check_validated',
    'transfer',
    transfer_row.id,
    jsonb_build_object(
      'checkKind', new.check_kind,
      'amountMinor', transfer_row.amount_minor,
      'currency', transfer_row.currency,
      'recipientName', transfer_row.recipient_name,
      'actionPath', '/myaccount'
    )
  )
  on conflict (event_key) do nothing;

  return new;
end;
$$;

revoke execute on function private.enqueue_transfer_check_validation_email()
  from public, anon, authenticated, service_role;

drop trigger if exists transfer_check_enqueue_validation_email
  on public.transfer_review_checks;

create trigger transfer_check_enqueue_validation_email
after update of status on public.transfer_review_checks
for each row
when (
  old.status is distinct from new.status
  and new.status = 'completed'
  and new.check_kind <> 'final_authorization'
)
execute function private.enqueue_transfer_check_validation_email();

create or replace function public.branch_manager_finalize_transfer(
  p_transfer_id uuid,
  p_note text default null
)
returns public.transfer_intents
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := private.ensure_branch_manager();
  transfer_row public.transfer_intents;
  position_row public.financial_positions;
  old_status text;
  normalized_note text := nullif(trim(coalesce(p_note, '')), '');
  ledger_description text := coalesce(
    normalized_note,
    'Virement confirmé après validation finale.'
  );
  generated_reference text;
  next_sequence bigint;
  ledger_entry_id uuid;
begin
  select * into transfer_row
  from public.transfer_intents
  where id = p_transfer_id
  for update;

  if not found then
    raise exception 'TRANSFER_NOT_FOUND' using errcode = 'P0002';
  end if;

  if transfer_row.status = 'under_review'
     and exists (
       select 1 from public.transfer_review_checks
       where transfer_id = p_transfer_id and status <> 'completed'
     ) then
    raise exception 'TRANSFER_REVIEW_CHECKS_INCOMPLETE' using errcode = '23514';
  end if;

  if transfer_row.status not in (
    'under_review', 'approved_for_external_execution', 'external_execution_recorded'
  ) then
    raise exception 'TRANSFER_NOT_READY_FOR_FINALIZATION' using errcode = '55000';
  end if;

  select * into position_row
  from public.financial_positions
  where id = transfer_row.source_position_id
    and owner_id = transfer_row.owner_id
  for update;

  if not found then
    raise exception 'TRANSFER_SOURCE_ACCOUNT_NOT_FOUND' using errcode = 'P0002';
  end if;
  if position_row.account_status <> 'active' then
    raise exception 'TRANSFER_SOURCE_ACCOUNT_NOT_ACTIVE' using errcode = '55000';
  end if;
  if position_row.amount_minor < transfer_row.amount_minor
     or position_row.reserved_minor < transfer_row.amount_minor then
    raise exception 'TRANSFER_POSITION_RECONCILIATION_CONFLICT' using errcode = '55000';
  end if;

  old_status := transfer_row.status;
  generated_reference := 'MONALYZ-TRF-' || upper(replace(transfer_row.id::text, '-', ''));

  select coalesce(max(sequence_no), 0) + 1 into next_sequence
  from public.financial_ledger_entries where account_id = position_row.id;

  insert into public.financial_ledger_entries (
    account_id, owner_id, sequence_no, entry_key, entry_kind, amount_minor,
    currency, balance_before_minor, balance_after_minor, value_date,
    internal_reference, source_transfer_id, booked_by, description, metadata
  ) values (
    position_row.id, transfer_row.owner_id, next_sequence,
    'transfer:' || transfer_row.id::text, 'transfer_debit', -transfer_row.amount_minor,
    transfer_row.currency, position_row.amount_minor,
    position_row.amount_minor - transfer_row.amount_minor, now(),
    generated_reference, transfer_row.id, caller_id, ledger_description,
    jsonb_build_object(
      'recipient_name', transfer_row.recipient_name,
      'target_amount_minor', transfer_row.target_amount_minor,
      'target_currency', transfer_row.target_currency
    )
  ) returning id into ledger_entry_id;

  update public.financial_positions
  set amount_minor = amount_minor - transfer_row.amount_minor,
      reserved_minor = reserved_minor - transfer_row.amount_minor,
      position_kind = 'internally_reconciled', as_of = now()
  where id = position_row.id;

  update public.transfer_intents
  set status = 'external_settlement_confirmed',
      internal_execution_reference = generated_reference,
      settled_by = caller_id, settled_at = now()
  where id = p_transfer_id
  returning * into transfer_row;

  insert into public.transfer_events (
    transfer_id, actor_id, event_type, from_status, to_status, reason, metadata
  ) values (
    p_transfer_id, caller_id, 'branch_manager_confirmed_effective_transfer',
    old_status, transfer_row.status, normalized_note,
    jsonb_build_object(
      'ledger_entry_id', ledger_entry_id,
      'internal_execution_reference', generated_reference
    )
  );

  insert into public.audit_events (
    actor_id, action, entity_type, entity_id, metadata
  ) values (
    caller_id, 'branch_manager_finalize_transfer', 'transfer_intent', p_transfer_id,
    jsonb_build_object(
      'from_status', old_status,
      'to_status', transfer_row.status,
      'ledger_entry_id', ledger_entry_id,
      'internal_execution_reference', generated_reference,
      'amount_minor', transfer_row.amount_minor,
      'currency', transfer_row.currency,
      'note', normalized_note
    )
  );

  insert into public.notifications (recipient_id, title, message, notification_type)
  values (
    transfer_row.owner_id, 'Virement effectué',
    'Votre virement a été confirmé comme effectué avec succès.', 'transfer'
  );

  return transfer_row;
end;
$$;

create or replace function public.branch_manager_review_transfer_check(
  p_transfer_id uuid,
  p_check_kind text,
  p_note text default null
)
returns public.transfer_intents
language plpgsql
security definer
set search_path = ''
as $$
declare
  transfer_row public.transfer_intents;
  check_row public.transfer_review_checks;
  caller_id uuid := private.ensure_branch_manager();
  normalized_note text := nullif(trim(coalesce(p_note, '')), '');
  expected_kind text;
  old_status text;
begin
  if p_check_kind not in ('dual_review', 'escalation', 'compliance', 'final_authorization') then
    raise exception 'INVALID_REVIEW_CHECK' using errcode = '22023';
  end if;

  select * into transfer_row
  from public.transfer_intents where id = p_transfer_id for update;
  if not found then
    raise exception 'TRANSFER_NOT_FOUND' using errcode = 'P0002';
  end if;
  if transfer_row.status in ('external_settlement_confirmed', 'rejected', 'cancelled', 'external_failed') then
    return transfer_row;
  end if;
  if transfer_row.status not in ('submitted', 'under_review') then
    raise exception 'TRANSFER_NOT_REVIEWABLE' using errcode = '55000';
  end if;

  select * into check_row
  from public.transfer_review_checks
  where transfer_id = p_transfer_id and check_kind = p_check_kind
  for update;
  if not found then
    raise exception 'TRANSFER_REVIEW_CHECK_NOT_FOUND' using errcode = 'P0002';
  end if;
  if check_row.status = 'completed' then
    return transfer_row;
  end if;

  expected_kind := case
    when not exists (select 1 from public.transfer_review_checks where transfer_id = p_transfer_id and check_kind = 'dual_review' and status = 'completed') then 'dual_review'
    when not exists (select 1 from public.transfer_review_checks where transfer_id = p_transfer_id and check_kind = 'escalation' and status = 'completed') then 'escalation'
    when not exists (select 1 from public.transfer_review_checks where transfer_id = p_transfer_id and check_kind = 'compliance' and status = 'completed') then 'compliance'
    else 'final_authorization'
  end;
  if p_check_kind <> expected_kind then
    raise exception 'TRANSFER_REVIEW_CHECK_OUT_OF_ORDER' using errcode = '55000';
  end if;

  old_status := transfer_row.status;

  update public.transfer_review_checks
  set status = 'completed', reviewer_id = caller_id, reviewed_at = now(),
      note = normalized_note
  where id = check_row.id;

  update public.transfer_intents set status = 'under_review'
  where id = p_transfer_id returning * into transfer_row;

  insert into public.transfer_events (
    transfer_id, actor_id, event_type, from_status, to_status, reason, metadata
  ) values (
    p_transfer_id, caller_id, 'review_check_updated', old_status,
    transfer_row.status, normalized_note,
    jsonb_build_object('check_kind', p_check_kind, 'check_status', 'completed')
  );

  if p_check_kind = 'final_authorization' then
    return public.branch_manager_finalize_transfer(p_transfer_id, normalized_note);
  end if;
  return transfer_row;
end;
$$;

grant execute on function public.branch_manager_review_transfer_check(uuid, text, text)
  to authenticated, service_role;
revoke execute on function public.branch_manager_review_transfer_check(uuid, text, text)
  from public, anon;

revoke execute on function public.branch_manager_finalize_transfer(uuid, text)
  from public, anon, authenticated;
grant execute on function public.branch_manager_finalize_transfer(uuid, text)
  to service_role;
